### ISSUE TITLE
Add "i" buttons to facets, opening explanatory text

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkod-registrovane-aplikace#21]
Inspired by the [Polish portal](https://dane.gov.pl/en/dataset?categories%5Bid%5D%5Bterms%5D=141) we should add "i" buttons to facets, with explanatory texts.
![image](https://github.com/datagov-cz/nkod-registrovane-aplikace/assets/718827/5777866c-33fa-45de-9bb9-125eeaaf148a)

Note that they act "on hover" on desktops and "on click" on mobile.

**Comment by skodapetr** [comment]
@jakubklimek Please add missing text for the tooltips, search for "TODO-TEXT".

**Comment by jakubklimek** [comment]
Done

**Comment by skodapetr** [comment]
There is an issue with tooltip position in Design System : https://github.com/datagov-cz/design-system/issues/20
