### ISSUE TITLE
Opening a dialog hides scrollbar, shifting the content

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkod-registrovane-aplikace#22]
![dialog shift](https://github.com/datagov-cz/nkod-registrovane-aplikace/assets/718827/10f1e8ff-3834-46ce-94d2-df0f780a7260)

**Comment by skodapetr** [comment]
Yes the issue is that the backdrop crops the size removing the scroll bar. This is an issue of the design system.
