### ISSUE TITLE
Publisher cards are not properly aligned

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkod-registrovane-aplikace#27]
The numbers of datasets go up and down...
![image](https://github.com/datagov-cz/nkod-registrovane-aplikace/assets/718827/671a4daf-85c0-4e68-a21b-b98f423908d8)

**Comment by skodapetr** [comment]
This is more of an issue of the design system.
On one hand we can pin the number of datasets to the bottom, but still the issue is that some headlines spans two lines. So we would actually need to pin down also the buttons leaving only the heading at the top.

**Comment by jakubklimek** [comment]
Which is how bootstrap does it....

**Comment by skodapetr** [comment]
I agree it makes sense, thus I belive we should implement it to Design System, at least our version.
