### ISSUE TITLE
Špatné zalomení při zobrazení katalogizačního záznamu

### ISSUE THREAD

**Issue by lenkakovacova89** [datagov-cz/nkod-registrovane-aplikace#31]
Příklad: https://data.gov.cz/datov%C3%A1-sada?iri=https%3A%2F%2Fdata.gov.cz%2Fzdroj%2Fdatov%C3%A9-sady%2F00020699%2F07e50072a5e6e71237a6cdbf696c978e 

![image](https://github.com/datagov-cz/nkod-registrovane-aplikace/assets/101256768/0a1f651a-01bb-45d6-ac11-a8fecee6e5e6)

**Comment by jakubklimek** [comment]
Zde je třeba říct, že hodnota je špatně už v LKODu. Proto se nezobrazuje jako název typu, ale jen jako IRI - a to se pak nevejde.
