### ISSUE TITLE
Check that we use dcat:inSeries instead of dcterms:isPartOf to detect membership in series

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/nkod-registrovane-aplikace#34]
Check that we use dcat:inSeries instead of dcterms:isPartOf to detect membership in series. We have a hotfix in the NKOD pipeline to add `dcterms:isPartOf`, but it should not be needed.

**Comment by skodapetr** [comment]
Seems like we are not using dcterms:isPartOf.
